/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as PenjualanRouteImport } from './routes/penjualan'
import { Route as PembelianRouteImport } from './routes/pembelian'
import { Route as MasterDataRouteImport } from './routes/master-data'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JurnalRouteImport } from './routes/jurnal'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformPendaftaranRouteImport } from './routes/platform.pendaftaran'
import { Route as PlatformBumdesRouteImport } from './routes/platform.bumdes'
import { Route as LaporanNeracaRouteImport } from './routes/laporan.neraca'
import { Route as LaporanLabaRugiRouteImport } from './routes/laporan.laba-rugi'
import { Route as LaporanKonsolidasiRouteImport } from './routes/laporan.konsolidasi'
import { Route as LaporanArusKasRouteImport } from './routes/laporan.arus-kas'

const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const PenjualanRoute = PenjualanRouteImport.update({
  id: '/penjualan',
  path: '/penjualan',
  getParentRoute: () => rootRouteImport,
} as any)
const PembelianRoute = PembelianRouteImport.update({
  id: '/pembelian',
  path: '/pembelian',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataRoute = MasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JurnalRoute = JurnalRouteImport.update({
  id: '/jurnal',
  path: '/jurnal',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformPendaftaranRoute = PlatformPendaftaranRouteImport.update({
  id: '/platform/pendaftaran',
  path: '/platform/pendaftaran',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformBumdesRoute = PlatformBumdesRouteImport.update({
  id: '/platform/bumdes',
  path: '/platform/bumdes',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanNeracaRoute = LaporanNeracaRouteImport.update({
  id: '/laporan/neraca',
  path: '/laporan/neraca',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanLabaRugiRoute = LaporanLabaRugiRouteImport.update({
  id: '/laporan/laba-rugi',
  path: '/laporan/laba-rugi',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanKonsolidasiRoute = LaporanKonsolidasiRouteImport.update({
  id: '/laporan/konsolidasi',
  path: '/laporan/konsolidasi',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanArusKasRoute = LaporanArusKasRouteImport.update({
  id: '/laporan/arus-kas',
  path: '/laporan/arus-kas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/dashboard': typeof DashboardRoute
  '/jurnal': typeof JurnalRoute
  '/login': typeof LoginRoute
  '/master-data': typeof MasterDataRoute
  '/pembelian': typeof PembelianRoute
  '/penjualan': typeof PenjualanRoute
  '/units': typeof UnitsRoute
  '/laporan/arus-kas': typeof LaporanArusKasRoute
  '/laporan/konsolidasi': typeof LaporanKonsolidasiRoute
  '/laporan/laba-rugi': typeof LaporanLabaRugiRoute
  '/laporan/neraca': typeof LaporanNeracaRoute
  '/platform/bumdes': typeof PlatformBumdesRoute
  '/platform/pendaftaran': typeof PlatformPendaftaranRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/dashboard': typeof DashboardRoute
  '/jurnal': typeof JurnalRoute
  '/login': typeof LoginRoute
  '/master-data': typeof MasterDataRoute
  '/pembelian': typeof PembelianRoute
  '/penjualan': typeof PenjualanRoute
  '/units': typeof UnitsRoute
  '/laporan/arus-kas': typeof LaporanArusKasRoute
  '/laporan/konsolidasi': typeof LaporanKonsolidasiRoute
  '/laporan/laba-rugi': typeof LaporanLabaRugiRoute
  '/laporan/neraca': typeof LaporanNeracaRoute
  '/platform/bumdes': typeof PlatformBumdesRoute
  '/platform/pendaftaran': typeof PlatformPendaftaranRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/dashboard': typeof DashboardRoute
  '/jurnal': typeof JurnalRoute
  '/login': typeof LoginRoute
  '/master-data': typeof MasterDataRoute
  '/pembelian': typeof PembelianRoute
  '/penjualan': typeof PenjualanRoute
  '/units': typeof UnitsRoute
  '/laporan/arus-kas': typeof LaporanArusKasRoute
  '/laporan/konsolidasi': typeof LaporanKonsolidasiRoute
  '/laporan/laba-rugi': typeof LaporanLabaRugiRoute
  '/laporan/neraca': typeof LaporanNeracaRoute
  '/platform/bumdes': typeof PlatformBumdesRoute
  '/platform/pendaftaran': typeof PlatformPendaftaranRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daftar'
    | '/dashboard'
    | '/jurnal'
    | '/login'
    | '/master-data'
    | '/pembelian'
    | '/penjualan'
    | '/units'
    | '/laporan/arus-kas'
    | '/laporan/konsolidasi'
    | '/laporan/laba-rugi'
    | '/laporan/neraca'
    | '/platform/bumdes'
    | '/platform/pendaftaran'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daftar'
    | '/dashboard'
    | '/jurnal'
    | '/login'
    | '/master-data'
    | '/pembelian'
    | '/penjualan'
    | '/units'
    | '/laporan/arus-kas'
    | '/laporan/konsolidasi'
    | '/laporan/laba-rugi'
    | '/laporan/neraca'
    | '/platform/bumdes'
    | '/platform/pendaftaran'
  id:
    | '__root__'
    | '/'
    | '/daftar'
    | '/dashboard'
    | '/jurnal'
    | '/login'
    | '/master-data'
    | '/pembelian'
    | '/penjualan'
    | '/units'
    | '/laporan/arus-kas'
    | '/laporan/konsolidasi'
    | '/laporan/laba-rugi'
    | '/laporan/neraca'
    | '/platform/bumdes'
    | '/platform/pendaftaran'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DaftarRoute: typeof DaftarRoute
  DashboardRoute: typeof DashboardRoute
  JurnalRoute: typeof JurnalRoute
  LoginRoute: typeof LoginRoute
  MasterDataRoute: typeof MasterDataRoute
  PembelianRoute: typeof PembelianRoute
  PenjualanRoute: typeof PenjualanRoute
  UnitsRoute: typeof UnitsRoute
  LaporanArusKasRoute: typeof LaporanArusKasRoute
  LaporanKonsolidasiRoute: typeof LaporanKonsolidasiRoute
  LaporanLabaRugiRoute: typeof LaporanLabaRugiRoute
  LaporanNeracaRoute: typeof LaporanNeracaRoute
  PlatformBumdesRoute: typeof PlatformBumdesRoute
  PlatformPendaftaranRoute: typeof PlatformPendaftaranRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penjualan': {
      id: '/penjualan'
      path: '/penjualan'
      fullPath: '/penjualan'
      preLoaderRoute: typeof PenjualanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pembelian': {
      id: '/pembelian'
      path: '/pembelian'
      fullPath: '/pembelian'
      preLoaderRoute: typeof PembelianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data': {
      id: '/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof MasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jurnal': {
      id: '/jurnal'
      path: '/jurnal'
      fullPath: '/jurnal'
      preLoaderRoute: typeof JurnalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/pendaftaran': {
      id: '/platform/pendaftaran'
      path: '/platform/pendaftaran'
      fullPath: '/platform/pendaftaran'
      preLoaderRoute: typeof PlatformPendaftaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/bumdes': {
      id: '/platform/bumdes'
      path: '/platform/bumdes'
      fullPath: '/platform/bumdes'
      preLoaderRoute: typeof PlatformBumdesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/neraca': {
      id: '/laporan/neraca'
      path: '/laporan/neraca'
      fullPath: '/laporan/neraca'
      preLoaderRoute: typeof LaporanNeracaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/laba-rugi': {
      id: '/laporan/laba-rugi'
      path: '/laporan/laba-rugi'
      fullPath: '/laporan/laba-rugi'
      preLoaderRoute: typeof LaporanLabaRugiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/konsolidasi': {
      id: '/laporan/konsolidasi'
      path: '/laporan/konsolidasi'
      fullPath: '/laporan/konsolidasi'
      preLoaderRoute: typeof LaporanKonsolidasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/arus-kas': {
      id: '/laporan/arus-kas'
      path: '/laporan/arus-kas'
      fullPath: '/laporan/arus-kas'
      preLoaderRoute: typeof LaporanArusKasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DaftarRoute: DaftarRoute,
  DashboardRoute: DashboardRoute,
  JurnalRoute: JurnalRoute,
  LoginRoute: LoginRoute,
  MasterDataRoute: MasterDataRoute,
  PembelianRoute: PembelianRoute,
  PenjualanRoute: PenjualanRoute,
  UnitsRoute: UnitsRoute,
  LaporanArusKasRoute: LaporanArusKasRoute,
  LaporanKonsolidasiRoute: LaporanKonsolidasiRoute,
  LaporanLabaRugiRoute: LaporanLabaRugiRoute,
  LaporanNeracaRoute: LaporanNeracaRoute,
  PlatformBumdesRoute: PlatformBumdesRoute,
  PlatformPendaftaranRoute: PlatformPendaftaranRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
