/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as PenjualanRouteImport } from './routes/penjualan'
import { Route as PembelianRouteImport } from './routes/pembelian'
import { Route as MasterDataRouteImport } from './routes/master-data'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JurnalRouteImport } from './routes/jurnal'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformPendaftaranRouteImport } from './routes/platform.pendaftaran'
import { Route as PlatformBumdesRouteImport } from './routes/platform.bumdes'
import { Route as LaporanNeracaRouteImport } from './routes/laporan.neraca'
import { Route as LaporanLabaRugiRouteImport } from './routes/laporan.laba-rugi'
import { Route as LaporanKonsolidasiRouteImport } from './routes/laporan.konsolidasi'
import { Route as LaporanArusKasRouteImport } from './routes/laporan.arus-kas'
import { Route as UnitDashboardUnitIdRouteImport } from './routes/unit.dashboard.$unitId'
import { Route as UnitDashboardUnitIdIndexRouteImport } from './routes/unit.dashboard.$unitId.index'
import { Route as UnitDashboardUnitIdSuppliersRouteImport } from './routes/unit.dashboard.$unitId.suppliers'
import { Route as UnitDashboardUnitIdSettingsRouteImport } from './routes/unit.dashboard.$unitId.settings'
import { Route as UnitDashboardUnitIdSalesRouteImport } from './routes/unit.dashboard.$unitId.sales'
import { Route as UnitDashboardUnitIdReportsRouteImport } from './routes/unit.dashboard.$unitId.reports'
import { Route as UnitDashboardUnitIdReceivablesRouteImport } from './routes/unit.dashboard.$unitId.receivables'
import { Route as UnitDashboardUnitIdPurchasesRouteImport } from './routes/unit.dashboard.$unitId.purchases'
import { Route as UnitDashboardUnitIdPayablesRouteImport } from './routes/unit.dashboard.$unitId.payables'
import { Route as UnitDashboardUnitIdJournalRouteImport } from './routes/unit.dashboard.$unitId.journal'
import { Route as UnitDashboardUnitIdInventoryRouteImport } from './routes/unit.dashboard.$unitId.inventory'
import { Route as UnitDashboardUnitIdCustomersRouteImport } from './routes/unit.dashboard.$unitId.customers'
import { Route as UnitDashboardUnitIdCashBankRouteImport } from './routes/unit.dashboard.$unitId.cash-bank'

const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const PenjualanRoute = PenjualanRouteImport.update({
  id: '/penjualan',
  path: '/penjualan',
  getParentRoute: () => rootRouteImport,
} as any)
const PembelianRoute = PembelianRouteImport.update({
  id: '/pembelian',
  path: '/pembelian',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataRoute = MasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JurnalRoute = JurnalRouteImport.update({
  id: '/jurnal',
  path: '/jurnal',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformPendaftaranRoute = PlatformPendaftaranRouteImport.update({
  id: '/platform/pendaftaran',
  path: '/platform/pendaftaran',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformBumdesRoute = PlatformBumdesRouteImport.update({
  id: '/platform/bumdes',
  path: '/platform/bumdes',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanNeracaRoute = LaporanNeracaRouteImport.update({
  id: '/laporan/neraca',
  path: '/laporan/neraca',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanLabaRugiRoute = LaporanLabaRugiRouteImport.update({
  id: '/laporan/laba-rugi',
  path: '/laporan/laba-rugi',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanKonsolidasiRoute = LaporanKonsolidasiRouteImport.update({
  id: '/laporan/konsolidasi',
  path: '/laporan/konsolidasi',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanArusKasRoute = LaporanArusKasRouteImport.update({
  id: '/laporan/arus-kas',
  path: '/laporan/arus-kas',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitDashboardUnitIdRoute = UnitDashboardUnitIdRouteImport.update({
  id: '/unit/dashboard/$unitId',
  path: '/unit/dashboard/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitDashboardUnitIdIndexRoute =
  UnitDashboardUnitIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UnitDashboardUnitIdRoute,
  } as any)
const UnitDashboardUnitIdSuppliersRoute =
  UnitDashboardUnitIdSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => UnitDashboardUnitIdRoute,
  } as any)
const UnitDashboardUnitIdSettingsRoute =
  UnitDashboardUnitIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => UnitDashboardUnitIdRoute,
  } as any)
const UnitDashboardUnitIdSalesRoute =
  UnitDashboardUnitIdSalesRouteImport.update({
    id: '/sales',
    path: '/sales',
    getParentRoute: () => UnitDashboardUnitIdRoute,
  } as any)
const UnitDashboardUnitIdReportsRoute =
  UnitDashboardUnitIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => UnitDashboardUnitIdRoute,
  } as any)
const UnitDashboardUnitIdReceivablesRoute =
  UnitDashboardUnitIdReceivablesRouteImport.update({
    id: '/receivables',
    path: '/receivables',
    getParentRoute: () => UnitDashboardUnitIdRoute,
  } as any)
const UnitDashboardUnitIdPurchasesRoute =
  UnitDashboardUnitIdPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => UnitDashboardUnitIdRoute,
  } as any)
const UnitDashboardUnitIdPayablesRoute =
  UnitDashboardUnitIdPayablesRouteImport.update({
    id: '/payables',
    path: '/payables',
    getParentRoute: () => UnitDashboardUnitIdRoute,
  } as any)
const UnitDashboardUnitIdJournalRoute =
  UnitDashboardUnitIdJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => UnitDashboardUnitIdRoute,
  } as any)
const UnitDashboardUnitIdInventoryRoute =
  UnitDashboardUnitIdInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => UnitDashboardUnitIdRoute,
  } as any)
const UnitDashboardUnitIdCustomersRoute =
  UnitDashboardUnitIdCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => UnitDashboardUnitIdRoute,
  } as any)
const UnitDashboardUnitIdCashBankRoute =
  UnitDashboardUnitIdCashBankRouteImport.update({
    id: '/cash-bank',
    path: '/cash-bank',
    getParentRoute: () => UnitDashboardUnitIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/dashboard': typeof DashboardRoute
  '/jurnal': typeof JurnalRoute
  '/login': typeof LoginRoute
  '/master-data': typeof MasterDataRoute
  '/pembelian': typeof PembelianRoute
  '/penjualan': typeof PenjualanRoute
  '/units': typeof UnitsRoute
  '/laporan/arus-kas': typeof LaporanArusKasRoute
  '/laporan/konsolidasi': typeof LaporanKonsolidasiRoute
  '/laporan/laba-rugi': typeof LaporanLabaRugiRoute
  '/laporan/neraca': typeof LaporanNeracaRoute
  '/platform/bumdes': typeof PlatformBumdesRoute
  '/platform/pendaftaran': typeof PlatformPendaftaranRoute
  '/unit/dashboard/$unitId': typeof UnitDashboardUnitIdRouteWithChildren
  '/unit/dashboard/$unitId/cash-bank': typeof UnitDashboardUnitIdCashBankRoute
  '/unit/dashboard/$unitId/customers': typeof UnitDashboardUnitIdCustomersRoute
  '/unit/dashboard/$unitId/inventory': typeof UnitDashboardUnitIdInventoryRoute
  '/unit/dashboard/$unitId/journal': typeof UnitDashboardUnitIdJournalRoute
  '/unit/dashboard/$unitId/payables': typeof UnitDashboardUnitIdPayablesRoute
  '/unit/dashboard/$unitId/purchases': typeof UnitDashboardUnitIdPurchasesRoute
  '/unit/dashboard/$unitId/receivables': typeof UnitDashboardUnitIdReceivablesRoute
  '/unit/dashboard/$unitId/reports': typeof UnitDashboardUnitIdReportsRoute
  '/unit/dashboard/$unitId/sales': typeof UnitDashboardUnitIdSalesRoute
  '/unit/dashboard/$unitId/settings': typeof UnitDashboardUnitIdSettingsRoute
  '/unit/dashboard/$unitId/suppliers': typeof UnitDashboardUnitIdSuppliersRoute
  '/unit/dashboard/$unitId/': typeof UnitDashboardUnitIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/dashboard': typeof DashboardRoute
  '/jurnal': typeof JurnalRoute
  '/login': typeof LoginRoute
  '/master-data': typeof MasterDataRoute
  '/pembelian': typeof PembelianRoute
  '/penjualan': typeof PenjualanRoute
  '/units': typeof UnitsRoute
  '/laporan/arus-kas': typeof LaporanArusKasRoute
  '/laporan/konsolidasi': typeof LaporanKonsolidasiRoute
  '/laporan/laba-rugi': typeof LaporanLabaRugiRoute
  '/laporan/neraca': typeof LaporanNeracaRoute
  '/platform/bumdes': typeof PlatformBumdesRoute
  '/platform/pendaftaran': typeof PlatformPendaftaranRoute
  '/unit/dashboard/$unitId/cash-bank': typeof UnitDashboardUnitIdCashBankRoute
  '/unit/dashboard/$unitId/customers': typeof UnitDashboardUnitIdCustomersRoute
  '/unit/dashboard/$unitId/inventory': typeof UnitDashboardUnitIdInventoryRoute
  '/unit/dashboard/$unitId/journal': typeof UnitDashboardUnitIdJournalRoute
  '/unit/dashboard/$unitId/payables': typeof UnitDashboardUnitIdPayablesRoute
  '/unit/dashboard/$unitId/purchases': typeof UnitDashboardUnitIdPurchasesRoute
  '/unit/dashboard/$unitId/receivables': typeof UnitDashboardUnitIdReceivablesRoute
  '/unit/dashboard/$unitId/reports': typeof UnitDashboardUnitIdReportsRoute
  '/unit/dashboard/$unitId/sales': typeof UnitDashboardUnitIdSalesRoute
  '/unit/dashboard/$unitId/settings': typeof UnitDashboardUnitIdSettingsRoute
  '/unit/dashboard/$unitId/suppliers': typeof UnitDashboardUnitIdSuppliersRoute
  '/unit/dashboard/$unitId': typeof UnitDashboardUnitIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/dashboard': typeof DashboardRoute
  '/jurnal': typeof JurnalRoute
  '/login': typeof LoginRoute
  '/master-data': typeof MasterDataRoute
  '/pembelian': typeof PembelianRoute
  '/penjualan': typeof PenjualanRoute
  '/units': typeof UnitsRoute
  '/laporan/arus-kas': typeof LaporanArusKasRoute
  '/laporan/konsolidasi': typeof LaporanKonsolidasiRoute
  '/laporan/laba-rugi': typeof LaporanLabaRugiRoute
  '/laporan/neraca': typeof LaporanNeracaRoute
  '/platform/bumdes': typeof PlatformBumdesRoute
  '/platform/pendaftaran': typeof PlatformPendaftaranRoute
  '/unit/dashboard/$unitId': typeof UnitDashboardUnitIdRouteWithChildren
  '/unit/dashboard/$unitId/cash-bank': typeof UnitDashboardUnitIdCashBankRoute
  '/unit/dashboard/$unitId/customers': typeof UnitDashboardUnitIdCustomersRoute
  '/unit/dashboard/$unitId/inventory': typeof UnitDashboardUnitIdInventoryRoute
  '/unit/dashboard/$unitId/journal': typeof UnitDashboardUnitIdJournalRoute
  '/unit/dashboard/$unitId/payables': typeof UnitDashboardUnitIdPayablesRoute
  '/unit/dashboard/$unitId/purchases': typeof UnitDashboardUnitIdPurchasesRoute
  '/unit/dashboard/$unitId/receivables': typeof UnitDashboardUnitIdReceivablesRoute
  '/unit/dashboard/$unitId/reports': typeof UnitDashboardUnitIdReportsRoute
  '/unit/dashboard/$unitId/sales': typeof UnitDashboardUnitIdSalesRoute
  '/unit/dashboard/$unitId/settings': typeof UnitDashboardUnitIdSettingsRoute
  '/unit/dashboard/$unitId/suppliers': typeof UnitDashboardUnitIdSuppliersRoute
  '/unit/dashboard/$unitId/': typeof UnitDashboardUnitIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daftar'
    | '/dashboard'
    | '/jurnal'
    | '/login'
    | '/master-data'
    | '/pembelian'
    | '/penjualan'
    | '/units'
    | '/laporan/arus-kas'
    | '/laporan/konsolidasi'
    | '/laporan/laba-rugi'
    | '/laporan/neraca'
    | '/platform/bumdes'
    | '/platform/pendaftaran'
    | '/unit/dashboard/$unitId'
    | '/unit/dashboard/$unitId/cash-bank'
    | '/unit/dashboard/$unitId/customers'
    | '/unit/dashboard/$unitId/inventory'
    | '/unit/dashboard/$unitId/journal'
    | '/unit/dashboard/$unitId/payables'
    | '/unit/dashboard/$unitId/purchases'
    | '/unit/dashboard/$unitId/receivables'
    | '/unit/dashboard/$unitId/reports'
    | '/unit/dashboard/$unitId/sales'
    | '/unit/dashboard/$unitId/settings'
    | '/unit/dashboard/$unitId/suppliers'
    | '/unit/dashboard/$unitId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daftar'
    | '/dashboard'
    | '/jurnal'
    | '/login'
    | '/master-data'
    | '/pembelian'
    | '/penjualan'
    | '/units'
    | '/laporan/arus-kas'
    | '/laporan/konsolidasi'
    | '/laporan/laba-rugi'
    | '/laporan/neraca'
    | '/platform/bumdes'
    | '/platform/pendaftaran'
    | '/unit/dashboard/$unitId/cash-bank'
    | '/unit/dashboard/$unitId/customers'
    | '/unit/dashboard/$unitId/inventory'
    | '/unit/dashboard/$unitId/journal'
    | '/unit/dashboard/$unitId/payables'
    | '/unit/dashboard/$unitId/purchases'
    | '/unit/dashboard/$unitId/receivables'
    | '/unit/dashboard/$unitId/reports'
    | '/unit/dashboard/$unitId/sales'
    | '/unit/dashboard/$unitId/settings'
    | '/unit/dashboard/$unitId/suppliers'
    | '/unit/dashboard/$unitId'
  id:
    | '__root__'
    | '/'
    | '/daftar'
    | '/dashboard'
    | '/jurnal'
    | '/login'
    | '/master-data'
    | '/pembelian'
    | '/penjualan'
    | '/units'
    | '/laporan/arus-kas'
    | '/laporan/konsolidasi'
    | '/laporan/laba-rugi'
    | '/laporan/neraca'
    | '/platform/bumdes'
    | '/platform/pendaftaran'
    | '/unit/dashboard/$unitId'
    | '/unit/dashboard/$unitId/cash-bank'
    | '/unit/dashboard/$unitId/customers'
    | '/unit/dashboard/$unitId/inventory'
    | '/unit/dashboard/$unitId/journal'
    | '/unit/dashboard/$unitId/payables'
    | '/unit/dashboard/$unitId/purchases'
    | '/unit/dashboard/$unitId/receivables'
    | '/unit/dashboard/$unitId/reports'
    | '/unit/dashboard/$unitId/sales'
    | '/unit/dashboard/$unitId/settings'
    | '/unit/dashboard/$unitId/suppliers'
    | '/unit/dashboard/$unitId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DaftarRoute: typeof DaftarRoute
  DashboardRoute: typeof DashboardRoute
  JurnalRoute: typeof JurnalRoute
  LoginRoute: typeof LoginRoute
  MasterDataRoute: typeof MasterDataRoute
  PembelianRoute: typeof PembelianRoute
  PenjualanRoute: typeof PenjualanRoute
  UnitsRoute: typeof UnitsRoute
  LaporanArusKasRoute: typeof LaporanArusKasRoute
  LaporanKonsolidasiRoute: typeof LaporanKonsolidasiRoute
  LaporanLabaRugiRoute: typeof LaporanLabaRugiRoute
  LaporanNeracaRoute: typeof LaporanNeracaRoute
  PlatformBumdesRoute: typeof PlatformBumdesRoute
  PlatformPendaftaranRoute: typeof PlatformPendaftaranRoute
  UnitDashboardUnitIdRoute: typeof UnitDashboardUnitIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penjualan': {
      id: '/penjualan'
      path: '/penjualan'
      fullPath: '/penjualan'
      preLoaderRoute: typeof PenjualanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pembelian': {
      id: '/pembelian'
      path: '/pembelian'
      fullPath: '/pembelian'
      preLoaderRoute: typeof PembelianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data': {
      id: '/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof MasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jurnal': {
      id: '/jurnal'
      path: '/jurnal'
      fullPath: '/jurnal'
      preLoaderRoute: typeof JurnalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/pendaftaran': {
      id: '/platform/pendaftaran'
      path: '/platform/pendaftaran'
      fullPath: '/platform/pendaftaran'
      preLoaderRoute: typeof PlatformPendaftaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/bumdes': {
      id: '/platform/bumdes'
      path: '/platform/bumdes'
      fullPath: '/platform/bumdes'
      preLoaderRoute: typeof PlatformBumdesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/neraca': {
      id: '/laporan/neraca'
      path: '/laporan/neraca'
      fullPath: '/laporan/neraca'
      preLoaderRoute: typeof LaporanNeracaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/laba-rugi': {
      id: '/laporan/laba-rugi'
      path: '/laporan/laba-rugi'
      fullPath: '/laporan/laba-rugi'
      preLoaderRoute: typeof LaporanLabaRugiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/konsolidasi': {
      id: '/laporan/konsolidasi'
      path: '/laporan/konsolidasi'
      fullPath: '/laporan/konsolidasi'
      preLoaderRoute: typeof LaporanKonsolidasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/arus-kas': {
      id: '/laporan/arus-kas'
      path: '/laporan/arus-kas'
      fullPath: '/laporan/arus-kas'
      preLoaderRoute: typeof LaporanArusKasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unit/dashboard/$unitId': {
      id: '/unit/dashboard/$unitId'
      path: '/unit/dashboard/$unitId'
      fullPath: '/unit/dashboard/$unitId'
      preLoaderRoute: typeof UnitDashboardUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unit/dashboard/$unitId/': {
      id: '/unit/dashboard/$unitId/'
      path: '/'
      fullPath: '/unit/dashboard/$unitId/'
      preLoaderRoute: typeof UnitDashboardUnitIdIndexRouteImport
      parentRoute: typeof UnitDashboardUnitIdRoute
    }
    '/unit/dashboard/$unitId/suppliers': {
      id: '/unit/dashboard/$unitId/suppliers'
      path: '/suppliers'
      fullPath: '/unit/dashboard/$unitId/suppliers'
      preLoaderRoute: typeof UnitDashboardUnitIdSuppliersRouteImport
      parentRoute: typeof UnitDashboardUnitIdRoute
    }
    '/unit/dashboard/$unitId/settings': {
      id: '/unit/dashboard/$unitId/settings'
      path: '/settings'
      fullPath: '/unit/dashboard/$unitId/settings'
      preLoaderRoute: typeof UnitDashboardUnitIdSettingsRouteImport
      parentRoute: typeof UnitDashboardUnitIdRoute
    }
    '/unit/dashboard/$unitId/sales': {
      id: '/unit/dashboard/$unitId/sales'
      path: '/sales'
      fullPath: '/unit/dashboard/$unitId/sales'
      preLoaderRoute: typeof UnitDashboardUnitIdSalesRouteImport
      parentRoute: typeof UnitDashboardUnitIdRoute
    }
    '/unit/dashboard/$unitId/reports': {
      id: '/unit/dashboard/$unitId/reports'
      path: '/reports'
      fullPath: '/unit/dashboard/$unitId/reports'
      preLoaderRoute: typeof UnitDashboardUnitIdReportsRouteImport
      parentRoute: typeof UnitDashboardUnitIdRoute
    }
    '/unit/dashboard/$unitId/receivables': {
      id: '/unit/dashboard/$unitId/receivables'
      path: '/receivables'
      fullPath: '/unit/dashboard/$unitId/receivables'
      preLoaderRoute: typeof UnitDashboardUnitIdReceivablesRouteImport
      parentRoute: typeof UnitDashboardUnitIdRoute
    }
    '/unit/dashboard/$unitId/purchases': {
      id: '/unit/dashboard/$unitId/purchases'
      path: '/purchases'
      fullPath: '/unit/dashboard/$unitId/purchases'
      preLoaderRoute: typeof UnitDashboardUnitIdPurchasesRouteImport
      parentRoute: typeof UnitDashboardUnitIdRoute
    }
    '/unit/dashboard/$unitId/payables': {
      id: '/unit/dashboard/$unitId/payables'
      path: '/payables'
      fullPath: '/unit/dashboard/$unitId/payables'
      preLoaderRoute: typeof UnitDashboardUnitIdPayablesRouteImport
      parentRoute: typeof UnitDashboardUnitIdRoute
    }
    '/unit/dashboard/$unitId/journal': {
      id: '/unit/dashboard/$unitId/journal'
      path: '/journal'
      fullPath: '/unit/dashboard/$unitId/journal'
      preLoaderRoute: typeof UnitDashboardUnitIdJournalRouteImport
      parentRoute: typeof UnitDashboardUnitIdRoute
    }
    '/unit/dashboard/$unitId/inventory': {
      id: '/unit/dashboard/$unitId/inventory'
      path: '/inventory'
      fullPath: '/unit/dashboard/$unitId/inventory'
      preLoaderRoute: typeof UnitDashboardUnitIdInventoryRouteImport
      parentRoute: typeof UnitDashboardUnitIdRoute
    }
    '/unit/dashboard/$unitId/customers': {
      id: '/unit/dashboard/$unitId/customers'
      path: '/customers'
      fullPath: '/unit/dashboard/$unitId/customers'
      preLoaderRoute: typeof UnitDashboardUnitIdCustomersRouteImport
      parentRoute: typeof UnitDashboardUnitIdRoute
    }
    '/unit/dashboard/$unitId/cash-bank': {
      id: '/unit/dashboard/$unitId/cash-bank'
      path: '/cash-bank'
      fullPath: '/unit/dashboard/$unitId/cash-bank'
      preLoaderRoute: typeof UnitDashboardUnitIdCashBankRouteImport
      parentRoute: typeof UnitDashboardUnitIdRoute
    }
  }
}

interface UnitDashboardUnitIdRouteChildren {
  UnitDashboardUnitIdCashBankRoute: typeof UnitDashboardUnitIdCashBankRoute
  UnitDashboardUnitIdCustomersRoute: typeof UnitDashboardUnitIdCustomersRoute
  UnitDashboardUnitIdInventoryRoute: typeof UnitDashboardUnitIdInventoryRoute
  UnitDashboardUnitIdJournalRoute: typeof UnitDashboardUnitIdJournalRoute
  UnitDashboardUnitIdPayablesRoute: typeof UnitDashboardUnitIdPayablesRoute
  UnitDashboardUnitIdPurchasesRoute: typeof UnitDashboardUnitIdPurchasesRoute
  UnitDashboardUnitIdReceivablesRoute: typeof UnitDashboardUnitIdReceivablesRoute
  UnitDashboardUnitIdReportsRoute: typeof UnitDashboardUnitIdReportsRoute
  UnitDashboardUnitIdSalesRoute: typeof UnitDashboardUnitIdSalesRoute
  UnitDashboardUnitIdSettingsRoute: typeof UnitDashboardUnitIdSettingsRoute
  UnitDashboardUnitIdSuppliersRoute: typeof UnitDashboardUnitIdSuppliersRoute
  UnitDashboardUnitIdIndexRoute: typeof UnitDashboardUnitIdIndexRoute
}

const UnitDashboardUnitIdRouteChildren: UnitDashboardUnitIdRouteChildren = {
  UnitDashboardUnitIdCashBankRoute: UnitDashboardUnitIdCashBankRoute,
  UnitDashboardUnitIdCustomersRoute: UnitDashboardUnitIdCustomersRoute,
  UnitDashboardUnitIdInventoryRoute: UnitDashboardUnitIdInventoryRoute,
  UnitDashboardUnitIdJournalRoute: UnitDashboardUnitIdJournalRoute,
  UnitDashboardUnitIdPayablesRoute: UnitDashboardUnitIdPayablesRoute,
  UnitDashboardUnitIdPurchasesRoute: UnitDashboardUnitIdPurchasesRoute,
  UnitDashboardUnitIdReceivablesRoute: UnitDashboardUnitIdReceivablesRoute,
  UnitDashboardUnitIdReportsRoute: UnitDashboardUnitIdReportsRoute,
  UnitDashboardUnitIdSalesRoute: UnitDashboardUnitIdSalesRoute,
  UnitDashboardUnitIdSettingsRoute: UnitDashboardUnitIdSettingsRoute,
  UnitDashboardUnitIdSuppliersRoute: UnitDashboardUnitIdSuppliersRoute,
  UnitDashboardUnitIdIndexRoute: UnitDashboardUnitIdIndexRoute,
}

const UnitDashboardUnitIdRouteWithChildren =
  UnitDashboardUnitIdRoute._addFileChildren(UnitDashboardUnitIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DaftarRoute: DaftarRoute,
  DashboardRoute: DashboardRoute,
  JurnalRoute: JurnalRoute,
  LoginRoute: LoginRoute,
  MasterDataRoute: MasterDataRoute,
  PembelianRoute: PembelianRoute,
  PenjualanRoute: PenjualanRoute,
  UnitsRoute: UnitsRoute,
  LaporanArusKasRoute: LaporanArusKasRoute,
  LaporanKonsolidasiRoute: LaporanKonsolidasiRoute,
  LaporanLabaRugiRoute: LaporanLabaRugiRoute,
  LaporanNeracaRoute: LaporanNeracaRoute,
  PlatformBumdesRoute: PlatformBumdesRoute,
  PlatformPendaftaranRoute: PlatformPendaftaranRoute,
  UnitDashboardUnitIdRoute: UnitDashboardUnitIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
